feat: test new pipeline with circleCI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,30 +2,169 @@
 # See: https://circleci.com/docs/reference/configuration-reference
 version: 2.1
 
+# Define reusable commands
+commands:
+  setup-docker-buildx:
+    description: "Setup Docker Buildx for multi-platform builds"
+    steps:
+      - run:
+          name: Setup Docker Buildx
+          command: |
+            docker buildx version
+            docker buildx create --name builder --use || true
+            docker buildx inspect --bootstrap
+
+  determine-image-tag:
+    description: "Determine the image tag based on branch/tag"
+    steps:
+      - run:
+          name: Determine image tag
+          command: |
+            if [ -n "$CIRCLE_TAG" ]; then
+              # Use git tag if available
+              IMAGE_TAG="$CIRCLE_TAG"
+            elif [ "$CIRCLE_BRANCH" = "master" ] || [ "$CIRCLE_BRANCH" = "main" ]; then
+              # Use commit SHA for main/master branch
+              IMAGE_TAG="${CIRCLE_SHA1:0:7}"
+            else
+              # Use branch name and commit SHA for other branches
+              IMAGE_TAG="${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7}"
+            fi
+            echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
+            echo "export FULL_IMAGE_NAME=ghcr.io/${GITHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}" >> $BASH_ENV
+            echo "export LATEST_IMAGE_NAME=ghcr.io/${GITHUB_USERNAME}/${IMAGE_NAME}:latest" >> $BASH_ENV
+            # Persist for other jobs
+            echo "$IMAGE_TAG" > /tmp/image_tag.txt
+            echo "${FULL_IMAGE_NAME}" > /tmp/full_image_name.txt
+            echo "${LATEST_IMAGE_NAME}" > /tmp/latest_image_name.txt
+
 # Define a job to be invoked later in a workflow.
 # See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
 jobs:
-  say-hello:
-    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/guides/execution-managed/executor-intro/ & https://circleci.com/docs/reference/configuration-reference/#executor-job
+  build:
     docker:
-      # Specify the version you desire here
-      # See: https://circleci.com/developer/images/image/cimg/base
       - image: cimg/base:current
-
-    # Add steps to the job
-    # See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#steps-overview & https://circleci.com/docs/reference/configuration-reference/#steps
+    environment:
+      IMAGE_NAME: k8s-ephemeral-storage-metrics
+      DOCKERFILE: Dockerfile
+      GITHUB_USERNAME: Bak3y
     steps:
-      # Checkout the code as the first step.
       - checkout
+      - setup-docker-buildx
+      - determine-image-tag
       - run:
-          name: "Say hello"
-          command: "echo Hello, World!"
+          name: Build Docker image (single platform for scanning)
+          command: |
+            docker buildx build \
+              --platform linux/amd64 \
+              --tag "${FULL_IMAGE_NAME}" \
+              --file "${DOCKERFILE}" \
+              --load \
+              .
+      - run:
+          name: Save image to tar for scanning
+          command: |
+            docker save "${FULL_IMAGE_NAME}" -o /tmp/image.tar
+      - persist_to_workspace:
+          root: /tmp
+          paths:
+            - image_tag.txt
+            - full_image_name.txt
+            - latest_image_name.txt
+            - image.tar
+
+  scan:
+    docker:
+      - image: cimg/base:current
+    environment:
+      IMAGE_NAME: k8s-ephemeral-storage-metrics
+      GITHUB_USERNAME: Bak3y
+    steps:
+      - attach_workspace:
+          at: /tmp
+      - run:
+          name: Load image metadata
+          command: |
+            export IMAGE_TAG=$(cat /tmp/image_tag.txt)
+            export FULL_IMAGE_NAME=$(cat /tmp/full_image_name.txt)
+            export LATEST_IMAGE_NAME=$(cat /tmp/latest_image_name.txt)
+            echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
+            echo "export FULL_IMAGE_NAME=$FULL_IMAGE_NAME" >> $BASH_ENV
+            echo "export LATEST_IMAGE_NAME=$LATEST_IMAGE_NAME" >> $BASH_ENV
+      - run:
+          name: Scan image for vulnerabilities
+          command: |
+            # Scan the image tar file before pushing using Trivy's official container
+            # Exit code 0 allows the build to continue even if vulnerabilities are found
+            # Change --exit-code 1 to fail the build on HIGH/CRITICAL vulnerabilities
+            docker run --rm \
+              -v /tmp:/tmp \
+              aquasec/trivy:latest image \
+              --input /tmp/image.tar \
+              --exit-code 0 \
+              --severity HIGH,CRITICAL \
+              --format table
+
+  push:
+    docker:
+      - image: cimg/base:current
+    environment:
+      IMAGE_NAME: k8s-ephemeral-storage-metrics
+      DOCKERFILE: Dockerfile
+      GITHUB_USERNAME: Bak3y
+    steps:
+      - checkout
+      - attach_workspace:
+          at: /tmp
+      - setup-docker-buildx
+      - run:
+          name: Load image metadata
+          command: |
+            export IMAGE_TAG=$(cat /tmp/image_tag.txt)
+            export FULL_IMAGE_NAME=$(cat /tmp/full_image_name.txt)
+            export LATEST_IMAGE_NAME=$(cat /tmp/latest_image_name.txt)
+            echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
+            echo "export FULL_IMAGE_NAME=$FULL_IMAGE_NAME" >> $BASH_ENV
+            echo "export LATEST_IMAGE_NAME=$LATEST_IMAGE_NAME" >> $BASH_ENV
+      - run:
+          name: Login to GitHub Container Registry
+          command: |
+            echo "$GITHUB_TOKEN" | docker login ghcr.io -u "${GITHUB_USERNAME}" --password-stdin
+      - run:
+          name: Build and push Docker image (multi-platform)
+          command: |
+            docker buildx build \
+              --platform linux/amd64,linux/arm64 \
+              --tag "${FULL_IMAGE_NAME}" \
+              --file "${DOCKERFILE}" \
+              --push \
+              .
+      - run:
+          name: Tag as latest (if on main/master branch)
+          command: |
+            if [ "$CIRCLE_BRANCH" = "master" ] || [ "$CIRCLE_BRANCH" = "main" ]; then
+              docker buildx imagetools create "${FULL_IMAGE_NAME}" --tag "${LATEST_IMAGE_NAME}"
+            fi
+      - run:
+          name: Output image information
+          command: |
+            echo "Successfully built and pushed:"
+            echo "  - ${FULL_IMAGE_NAME}"
+            if [ "$CIRCLE_BRANCH" = "master" ] || [ "$CIRCLE_BRANCH" = "main" ]; then
+              echo "  - ${LATEST_IMAGE_NAME}"
+            fi
 
 # Orchestrate jobs using workflows
 # See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
 workflows:
-  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
-    # Inside the workflow, you define the jobs you want to run.
+  build-scan-push:
+    # Run on all pushes and tags
+    # To limit to specific branches, add filters to the jobs below
     jobs:
-      - say-hello
+      - build
+      - scan:
+          requires:
+            - build
+      - push:
+          requires:
+            - scan
